version: '3.7'

services:
    elasticsearch:
        image: elasticsearch:7.13.4
        container_name: elasticsearch
        privileged: true
        environment:
            - cluster.name=elasticsearch #设置集群名称
            - discovery.type=single-node #以单一节点启动
            - "ES_JAVA_OPTS=-Xms512m -Xmx1096m" #设置jvm内存大小
            - bootstrap.memory_lock=true
        volumes:
            - /etc/localtime:/etc/localtime
            - ./es/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
            - ./es/data:/usr/share/elasticsearch/data:rw #数据文件挂载
            - ./es/logs:/usr/share/elasticsearch/logs:rw
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - estack
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: 1024M
                reservations:
                    memory: 200M
    kibana:
        image: kibana:7.13.4
        container_name: kibana
        depends_on:
            - elasticsearch
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
            I18N_LOCALE: zh-CN
        volumes:
            - /etc/localtime:/etc/localtime
        ports:
            - "5601:5601"
        networks:
            - estack
networks:
    estack:
